checks:
    php:
        code_rating: true
        duplication: true
        
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
        
build:
    dependencies:
        after:
            - php -r "file_exists('.env') || copy('.env.scrutinizer', '.env');"
            - php artisan key:generate

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    
    tests-and-coverage:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=xrsites'
                coverage:
                    file: 'xrsites'
                    format: 'clover'
