checks:
    php:
        code_rating: true
        duplication: true
        
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
        
build:
    dependencies:
        before:
            - composer install --no-interaction --prefer-dist --no-suggest
            - php -r "file_exists('.env') || copy('.env.scrutinizer', '.env');"
            - php artisan key:generate
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=xrsites'
                coverage:
                    file: 'xrsites'
                    format: 'clover'
