checks:
    php:
        code_rating: true
        duplication: true
        
filter:
    excluded_paths: [vendor/*]
    excluded_paths: [tests/*]

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
        
build:
    dependencies:
        before:
            - php artisan key:generate
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=xrsites'
                coverage:
                    file: 'xrsites'
                    format: 'clover'
