language: php

php:
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - setup=basic
    - TESTER_PHP_BIN="php-cgi"
    - TESTER_PHP_BIN="hhvm"

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: 7.1
      env: TESTER_PHP_BIN="hhvm"

    - php: 7.2
      env: TESTER_PHP_BIN="hhvm"

    - php: hhvm
      env: TESTER_PHP_BIN="php-cgi"


sudo: false

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 && $TRAVIS_PHP_VERSION != "hhvm" ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry $TESTER_PHP_BIN composer.phar self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry $TESTER_PHP_BIN composer.phar install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry $TESTER_PHP_BIN composer.phar update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry $TESTER_PHP_BIN composer.phar update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - $TESTER_PHP_BIN -r "file_exists('.env') || copy('.env.example', '.env');"
  - $TESTER_PHP_BIN artisan key:generate
  - touch database/database.sqlite

script: vendor/bin/phpunit
