language: php

php:
  - 7.1
  - 7.2
  - hhvm
  - nightly

env:
  global:
    - setup=basic

sudo: false

cache:
  directories:
    - $HOME/.composer/cache


before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi
  - php -r "file_exists('.env') || copy('.env.example', '.env');"
  - php artisan key:generate
  - touch database/database.sqlite

script: vendor/bin/phpunit
