<?php

namespace Tests\Unit\App;

use Tests\TestCase;
use App\LoginUser;
use Laravel\Socialite\Facades\Socialite;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2017-12-16 at 16:44:41.
 */
class LoginUserTest extends TestCase {

    /**
     * @var LoginUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->object = new LoginUser;
    }

    /**
     * @covers App\LoginUser::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        $provider = \Mockery::mock('Laravel\Socialite\Contracts\Provider');
        $provider->shouldReceive('redirect')->andReturn('Redirected');
        $provider->shouldReceive('with')->with(["access_type" => "offline", "prompt" => "consent select_account"])->andReturnSelf();
        Socialite::shouldReceive('driver')->once()->with('google')->andReturn($provider);
        $returnValue = $this->object->authenticate('google');
        $this->assertEquals($returnValue, 'Redirected');
    }

    /**
     * @covers App\LoginUser::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
